// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt4R2AYD79C_DXmKQYZOIGEjwGMwkQDD0',
    appId: '1:188285573314:web:12645623f8a009b803c35b',
    messagingSenderId: '188285573314',
    projectId: 'task-app-c96a4',
    authDomain: 'task-app-c96a4.firebaseapp.com',
    storageBucket: 'task-app-c96a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANsWdE_Zb9s-kV4hA0ZQZ-vZE09Dv_9Vs',
    appId: '1:188285573314:android:50bdfef60bfe115703c35b',
    messagingSenderId: '188285573314',
    projectId: 'task-app-c96a4',
    storageBucket: 'task-app-c96a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxdEYvdoKQZklnaB9qNpmvxzkHWa3Bkus',
    appId: '1:188285573314:ios:f394d6ea71f91b9603c35b',
    messagingSenderId: '188285573314',
    projectId: 'task-app-c96a4',
    storageBucket: 'task-app-c96a4.appspot.com',
    iosBundleId: 'com.dmgcoding.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxdEYvdoKQZklnaB9qNpmvxzkHWa3Bkus',
    appId: '1:188285573314:ios:3777a50f3865c24203c35b',
    messagingSenderId: '188285573314',
    projectId: 'task-app-c96a4',
    storageBucket: 'task-app-c96a4.appspot.com',
    iosBundleId: 'com.dmgcoding.taskApp.RunnerTests',
  );
}
